name: pr-to-master

on:
  push:
    branches:
      - dev

jobs:
  pr-to-master:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'version updates')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
      - run: git fetch origin dev
      - run: git read-tree -u --reset ${{ github.sha }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.head_commit.message }}
          branch: release/master
          branch-suffix: short-commit-hash
          title: Publish
          body: |
            Merging this PR will squash and push all changes to the master branch.
            It will kick off the process to release and publish any packages with an incremented version number.
