name: pr-to-master

on:
  push:
    branches:
      - dev

jobs:
  pr-to-master:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Publish')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
      - run: git fetch origin dev
      - run: git read-tree -u --reset ${{ github.sha }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.head_commit.message }}
          title: Publish
