name: release

on:
  push:
    branches:
      - dev

jobs:
  dump:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Publish')
    steps:
      - uses: actions/checkout@v2
      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
      - run: git fetch origin master
      - run: git checkout master
      - run: git merge --squash ${{ github.sha }} -s recursive -X theirs --allow-unrelated-histories
      - run: git commit -m "${{ github.event.head_commit.message }}"
      - run: git push

  publish-npm:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: git status
      - name: Login to NPM
        run: echo "npm login" # npm login ${{ secrets.npm_token }}
      - name: Publish package
        run: |
          cd cli/tauri.js
          echo "We will publish this directory."
          ls # npm publish

  publish-cargo:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: git status
      - name: Login to Crates.IO
        run: echo "cargo login" # cargo login ${{ secrets.crate_token }}
      - name: Publish CLI
        run: |
          cd cli/tauri-cli
          echo "We will publish this directory."
          ls # cargo publish
      - name: Publish TAURI
        run: |
          cd tauri
          echo "We will publish this directory."
          ls # TAURI_DIST_DIR=../../test/fixture/dist cargo publish
